# Generated by Django 5.2 on 2026-05-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_booking_id_alter_notification_id_alter_slot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
